### ISSUE TITLE
can't create parser in IE Worker

### ISSUE THREAD

**Issue by ericvergnaud** [letorbi/smoothie#13]
Hi Torben,
not sure where Smoothie is going, but I thought you might have a solution for the below:
var parser = URL ? new URL(location.href) : document.createElement('A');
in IE in a web worker.

IE 10 has no support for URL and workers cannot create DOM objects.
As a result, using require from a web worker fails. I can't seem to think of a solution...
Eric

**Comment by ericvergnaud** [comment]
3 hours later, came up with the below:

```
    var parser = (function() {
        try {
        	return new URL(location.href);
        } catch(e) {
        	var p = Object.create(location);
        	// need to set writable, because WorkerLocation is read-only
        	Object.defineProperty(p, "href", {writable:true});
        	return p;
        }
    })();
```

what do you think?

**Comment by letorbi** [comment]
Hej Eric,

first of all thanks for your efforts to improve Smoothie.

Unfortunately your replacement code isn't working proerly since the URL won't be normalized (e.g. turning */foo/../bar///baz* into */bar/baz*) this way. This can cause unexpected bahaviour since the module IDs *my/module* and *my/./module* are treated as differend modules, even though they refence the same.

I'm working on a solution and will post it here the next few days...

Bai
Torben

**Comment by ericvergnaud** [comment]
Noted :-)

Envoyé de mon iPhone

**Comment by letorbi** [comment]
Hej Eric,

it took me some time, but now I've created a simple, yet incomplete, polyfill for the URL constructor:

https://gist.github.com/letorbi/c14128d23cd8473fc6ea0627176a812a

Just include the code before you load Smoothie an it should work in IE10.

In case you might wonder: I've decided not to include the polyfill directly into Smoothie because it would bloat the code just to fix a very rare usecase. I hope you undersand :)

Please let me know if it work, so that I can close the issue.

Bai
Torben

**Comment by ericvergnaud** [comment]
Hi Torben,
thanks for this. It works for me.
I did integrate it into require.js, because what it needs is not a URL replacement but rather a parser, so in case using URL fails, I fallback to your inlined polyfill, which avoids checking the context.
Eric

**Comment by letorbi** [comment]
I've found a better URL polyfill: https://github.com/lifaon74/url-polyfill

**Comment by ericvergnaud** [comment]
Thanks Torben
